kind: ConfigMap
apiVersion: v1
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    cluster.name: "elk-cluster" 
    network.host: 0.0.0.0
    xpack.license.self_generated.type: basic 
    xpack.monitoring.collection.enabled: true
    xpack.ml.enabled: false
